name: securely
description: "Securely is a flutter plugin for Runtime Application Self-Protection (RASP)."
version: 0.0.4
homepage: https://github.com/Al-Fuad/Securely

topics:
  - secure
  - security
  - root-detection
  - debugger-detection
  - frida-detection

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.alfuad.securely
        pluginClass: SecurelyPlugin
      ios:
        pluginClass: SecurelyPlugin

