name: archit
description: A powerful CLI tool to scaffold Flutter projects with clean architecture.
version: 0.0.3
repository: https://github.com/Al-Fuad/Packages/tree/main/flutter/archit

topics: 
  - cli
  - flutter
  - clean-architecture
  - scaffold
  - generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0

executables:
  archit:

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
